# Generated by Django 4.1.9 on 2024-03-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
