# Generated by Django 4.1.9 on 2024-03-01 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_rename_content_question_question_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
